development:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: 120646598750
  store: patricksherwin.myshopify.com
  ignore_files:
    - "*.gif"
    - "settings_data.json"
  

staging:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${STAGING_THEME_ID}
  store: patricksherwin.myshopify.com
  ignore_files:
     - "settings_data.json"

  
production:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: 80319053918
  store: patricksherwin.myshopify.com
  ignore_files:
    - "settings_data.json"

  
bundles:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: 120632016990
  store: patricksherwin.myshopify.com
  ignore_files:
    - "*.gif"
    - "settings_data.json"

pdp:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: 120646598750
  store: patricksherwin.myshopify.com
  ignore_files:
    - "*.gif"
    - "settings_data.json"

